[WIP]chat-spaceデータベース設計案
yuppi0809/chat-space pull request #1
Opened 2019-02-06 10:03 UTC by yuppi0809

#WHAT
chat-spaceのデータベース設計案
#WHY
データベース設計は必要不可欠のため

2019-02-06 10:12 UTC, TOMARUMARU reviewed
明らかにアソシエーションが足りていません。
多対多のアソシエーションの組み方について調べて修正をお願いします。

2019-02-06 10:12 UTC, TOMARUMARU commented on README.md
> +|group_name|string|null: false, unique: true|
nameという名前で十分です

2019-02-06 10:12 UTC, TOMARUMARU commented on README.md
> +|body|text|none|
noneとはなんでしょう？

2019-02-06 11:16 UTC, yuppi0809 commented on README.md
> +|group_name|string|null: false, unique: true|
変更しました。

2019-02-06 11:16 UTC, yuppi0809 commented on README.md
> +|body|text|none|
「なし」の意でnoneとしました。削除しました。

2019-02-06 11:21 UTC, TOMARUMARU reviewed
groupsとusersはmembersを中間テーブルとして多対多の関係になります。
よく調べてアソシエーションの修正をお願いします。

2019-02-06 11:41 UTC, yuppi0809 commented
中間テーブルを通した多対多の関係についてのRails Guideの該当すると思われる部分をみて訂正しました。あってますでしょうか。

2019-02-06 11:43 UTC, TOMARUMARU commented on README.md
> +- has many :groups, through: :members
いいですね！
別途has_many: membersが必要になります。

2019-02-06 11:43 UTC, TOMARUMARU commented on README.md
> +- has many :users, through: :members
こちらも同様です

2019-02-06 11:52 UTC, yuppi0809 commented on README.md
> +- has many :users, through: :members
ありがとうございます。has_many: membersを追加しました。

2019-02-06 11:52 UTC, yuppi0809 commented on README.md
> +- has many :groups, through: :members
has_many: membersを追加しました。

2019-02-06 12:02 UTC, yuki-uchida requested changes

2019-02-06 12:02 UTC, yuki-uchida commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
外部テーブルのidと紐づける場合には、refferenceとしましょう！

2019-02-06 12:02 UTC, yuki-uchida commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
こちらも

2019-02-06 12:28 UTC, yuppi0809 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referencesの記述を追加しました。カリキュラムで、マイグレーションファイルに、t.string :カラム名などと並列でt.references: テーブル名, foreign-key: trueと記述すると習ったのでその部分を参照しました。

2019-02-08 09:34 UTC, yuppi0809 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referenceを使いました。

2019-02-08 09:34 UTC, yuppi0809 commented on README.md
> +|group_id|integer|null: false, foreign_key: true|
referenceを使いました。

2019-02-08 09:42 UTC, yuki-uchida commented
LGTMです！

2019-02-08 09:50 UTC, merged